### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/idyll#114]
This issue is to discuss and prioritize upcoming work. I think/hope this will make things sufficiently polished to warrant a v2 release. My hope is that between myself and @mathisonian (and anyone else who wants to help!) we can complete these items by the end of August.

- [x] Move to a monorepo structure using Yarn workspaces ([announcement post preview](https://deploy-preview-580--yarnpkg.netlify.com/blog/2017/07/26/introducing-workspaces/))
- [x] Clean up and refine `idyll-interactive-document`, specifically the walkers
- [ ] Improve tests
- [x] Re-enable Travis for the monorepo
- [x] Curate and add to the list of default components (will create a separate issue to discuss in detail)
- [x] Remove the need for `idyll-component` and improve support for plain React components
- [ ] Ensure editor code is production-ready
- [x] Clean up compiler related to issues mentioned below
- [x] [Adopt React 16](https://github.com/facebook/react/issues/10294)
- [ ] Fill out and update READMEs for all packages
- [x] Update site docs
- [x] Ensure site has at least basic sponsorship info
- [ ] Getting `idyll-editor` publishing to idyll-lang.github.io/editor
- [x] Deprecate old packages (idyll-interactive-document, idyll-component, generator?)

**Comment by mathisonian** [comment]
This seems like a great list. 

I'd also like to do some cleanup on the compiler (specifically around nesting nodes https://github.com/idyll-lang/idyll-compiler/issues/28, https://github.com/idyll-lang/idyll-compiler/issues/20), and add in transforms (https://github.com/idyll-lang/idyll/issues/70) since that shouldn't be too much added code but will enable a lot of functionality.

**Comment by bclinkinbeard** [comment]
Cool, updated the original comment with items for compiler work and React 16, and turned it into a task list. :)

**Comment by mathisonian** [comment]
I've gone ahead and tagged outstanding issues with the `v2` label to help track what seems reasonable to get in for the initial release

**Comment by bclinkinbeard** [comment]
Awesome. I may try to do a prerelease in the next few days just to iron out the process and make it easier to test in real world scenarios.

Would version as alpha or beta and publish as `idyll@next`. You OK with that?

**Comment by mathisonian** [comment]
Sounds good to me

**Comment by bclinkinbeard** [comment]
Woohoo, `2.0.0-alpha.2` versions of everything but the compiler have been published under the `next` tag. (I don't have permission to publish compiler if you can fix that.)

https://yarnpkg.com/en/package/idyll
https://yarnpkg.com/en/package/idyll-components
https://yarnpkg.com/en/package/idyll-document
https://yarnpkg.com/en/package/idyll-editor

I also updated the list with some other tasks
