### ISSUE TITLE
React 16 warnings

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#184]
The following warnings still appear when installing dependencies with yarn:

```
warning "react-inlinesvg@0.6.2" has incorrect peer dependency "react@^0.14 || ^15.0".
warning "react-latex@1.0.1" has incorrect peer dependency "react@^15.3.0".
warning "react-table@6.5.3" has incorrect peer dependency "react@^15.x.x".
warning "draft-js@0.10.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-rc".
warning "draft-js@0.10.2" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-rc".
```

- [x] `react-table` has an issue open https://github.com/react-tools/react-table/issues/511 but haven't released a new version to npm
- [x] `draft-js` has an issue here https://github.com/facebook/draft-js/issues/1411 and open PR https://github.com/facebook/draft-js/pull/1422
- [x] `react-latex` doesn't have an issue.
- [x] `react-inlinesvg` has an issue https://github.com/matthewwithanm/react-inlinesvg/issues/67 and a PR https://github.com/matthewwithanm/react-inlinesvg/pull/68
